[package]
name = "d8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.7"
num = "0.4.1"


[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=native"]
